const jokes = [
    {
        category: "Programming",
        type: "single",
        joke: "I've got a really good UDP joke to tell you but I don't know if you'll get it.",
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 0,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: 'A guy walks into a bar and asks for 1.4 root beers.\nThe bartender says "I\'ll have to charge you extra, that\'s a root beer float".\nThe guy says "In that case, better make it a double."',
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 2,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: "A programmer puts two glasses on his bedside table before going to sleep.\nA full one, in case he gets thirsty, and an empty one, in case he doesn't.",
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 3,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: "Java and C were telling jokes. It was C's turn, so he writes something on the wall, points to it and says \"Do you get the reference?\" But Java didn't.",
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 4,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: 'A SQL statement walks into a bar and sees two tables.\nIt approaches, and asks "may I join you?"',
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 5,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: "Your mama's so FAT she can't save files bigger than 4GB.",
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: true,
        },
        id: 9,
        safe: false,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: "// This line doesn't actually do anything, but the code stops working when I delete it.",
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 12,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: '"Honey, go to the store and buy some eggs."\n"OK."\n"Oh and while you\'re there, get some milk."\nHe never returned.',
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 18,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: '"We messed up the keming again guys."',
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 20,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: '"A programmer had a problem. He decided to use Java. He now has a ProblemFactory."',
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 20,
        safe: true,
        lang: "en",
    },
];

const jokeEl = document.getElementById("joke");
console.log(jokes.length);
let index = Math.floor(Math.random() * jokes.length);
jokeEl.innerHTML = jokes[index].joke;
