/*
Write a JavaScript program to pretend to look like a hacker. Write an asynchronous function that will simply display the following output:

Initializing hack program...
Hacking Ashish username...
Username found: aashish17...
Connecting to Facebook...

Try to use HTML and styling if possible.
*/
